name: tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      # Set up the dev command prompt, so that cl.exe is in the path. This has
      # no effect outside of Windows.
      - uses: ilammy/msvc-dev-cmd@v1
      - run: python test.py
